source :rubygems

gem 'sinatra'
gem 'shotgun'
gem 'haml'
if RUBY_VERSION < '1.9'
  gem "ruby-debug", ">= 0.10.3"
else
  gem "ruby-debug19", :require => 'ruby-debug'
end

gem 'cloud_factory', :path => "../../"